# -*- coding: utf-8 -*-
"""snowflake.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O3XJxX7o6VhKcVmnHpdSKq2zjYG7FSvw
"""

!pip install snowflake-connector-python

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics
from sklearn.tree import plot_tree
import matplotlib.pyplot as plt
import snowflake.connector
conn = snowflake.connector.connect(
    user='GOKILA',
    password= 'Btsarmy0739177',
    account= 'TGULZJN-YG81730',
    database= 'HEART',
    schema= 'PUBLIC',
    warehouse= 'COMPUTE_WH'
)

query = "SELECT * from heart"
df = pd.read_sql(query,conn)
df

df.head()

df.tail()

df.shape

df.info()

df.describe()

df.isnull().sum()

from scipy.stats import zscore
z_scores = zscore(df)
df[np.abs(z_scores)>2.5]

log_transform = np.log1p(df)

print(log_transform.head())

from scipy.stats import zscore
z_scores = zscore(df)
df[np.abs(z_scores)>2.5]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

dt_model = DecisionTreeClassifier(
    criterion='entropy',
    max_depth=4,
    random_state=42
)

X = log_transform.drop("TARGET", axis=1)

# Use original TARGET column (not log transformed)
y = df["TARGET"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(
    criterion='entropy',
    max_depth=4,
    random_state=42
)

dt_model.fit(X_train, y_train)

# Prediction
y_pred = dt_model.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report

print("Accuracy :", accuracy_score(y_test, y_pred))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

plt.figure(figsize=(20,10))

plot_tree(
    dt_model,
    feature_names=X.columns,
    class_names=['0', '1'],
    filled=True
)

plt.show()